name: pickmed
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#Version
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  date_time_format: ^2.0.1
  intl: ^0.18.0
  get: ^4.6.6
  get_it: ^7.1.3
  provider: ^6.1.1
  modal_progress_hud_nsn: ^0.5.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  cool_alert: ^2.0.1
  firebase_storage: ^12.0.1
  firebase_core: ^3.1.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.3
  country_picker: ^2.0.26
  pinput: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/dynamic_assets/
    - assets/static_assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
  - family: Barlow
    fonts:
      - asset: assets/fonts_family/barlow/Barlow-Light.ttf
        weight: 400
      - asset: assets/fonts_family/barlow/Barlow-Medium.ttf
        weight: 700
      - asset: assets/fonts_family/barlow/Barlow-Regular.ttf
        weight: 500
      - asset: assets/fonts_family/barlow/Barlow-Bold.ttf
        weight: 700
  - family: Allerta
    fonts:
      - asset: assets/fonts_family/Allerta/Allerta-Regular.ttf
        weight: 400

       
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
